### ISSUE TITLE
Web UI for chat & settings

### ISSUE THREAD

**Issue by innovinitylabs** [sidetrip-ai/ici-core#45]
# WEB UI FOR CHAT & SETTINGS

### Issue Type
Enhancement/Bug Fix

### Current Issues
1. **Chat Response Issues**
   - Repetitive responses from the AI
   - System prompt being included in responses
   - Blank outputs in some cases
   - Issues with deepseek model responses

2. **Security Restrictions**
   - Web UI access being blocked by validator
   - CLI-only access configuration

3. **Configuration Management**
   - Need for better model configuration options
   - Prompt template formatting issues
   - Memory and context handling

#### 1. Web UI Implementation
Created a new web interface (`examples/sidetrip_chat_ui.py`) with:
- Real-time chat using WebSocket
- Configuration management panel
- Model selection options
- Memory settings
- System prompt editor

#### 2. Security Configuration
Updated `config.yaml` validator settings:
```yaml
validator:
  allowed_sources:
    - COMMAND_LINE
    - web
  rules:
    - type: source
      allowed: [COMMAND_LINE, web]
    - type: permission_level
      allowed: [user, admin]
```

#### 3. Generator Settings
Added comprehensive model configuration options:
```yaml
generator:
  default_options:
    temperature: 0.7
    max_tokens: 1024
    frequency_penalty: 0.0
    presence_penalty: 0.0
    top_p: 1.0
  memory:
    type: buffer
    k: 5
```

#### 4. UI Features
- Real-time chat with typing indicators
- Settings panel for all configurations
- Error handling and display
- Mobile-responsive design
- Chat history management
- Message formatting support

### Required Dependencies
```bash
pip install fastapi uvicorn python-multipart jinja2 aiofiles
```

### Testing Steps
1. Install dependencies
2. Update config.yaml with new validator settings
3. Start the web UI:
```bash
python examples/sidetrip_chat_ui.py --config /path/to/config.yaml --port 8008
```
4. Test the following:
   - Chat functionality
   - Model configuration changes
   - Security access from both web and CLI
   - Response formatting
   - Error handling

### Related Components
- Web UI (`examples/sidetrip_chat_ui.py`)
- Configuration (`config.yaml`)
- Templates (`examples/templates/chat.html`)
- Validator settings
- Generator configuration
- Memory management

### Documentation Updates Needed
1. Web UI Usage Guide
   - Installation and setup
   - Available configuration options
   - Security settings

2. Configuration Reference
   - Validator settings
   - Model options
   - Memory settings
   - Prompt templates

3. Development Guide
   - WebSocket implementation
   - Configuration management
   - Error handling
   - UI customization

### Additional Notes
- The web UI provides a modern interface for interacting with the AI
- Security is maintained through explicit validation rules
- Configuration changes are persisted to config.yaml
- Real-time updates for all settings
- Support for multiple models and configurations
- Improved error handling and user feedback

### Future Improvements
1. Add user authentication and role-based access
2. Implement configuration presets
3. Add chat history export/import
4. Improve response streaming
5. Add model performance metrics
6. Implement better error recovery
7. Add configuration version control
